# Generated by Django 4.2.7 on 2023-11-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_department_alter_employee_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
            options={
                'verbose_name': 'Подтверждение сотрудника',
                'verbose_name_plural': 'Подтверждения сотрудников',
            },
        ),
    ]
