# Generated by Django 4.2.7 on 2023-11-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employeeconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complexity',
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Очень легкая'), (2, 'Легкая'), (3, 'Средняя'), (4, 'Трудная'), (5, 'Очень трудная')], default=1),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
    ]
