# Generated by Django 4.2.7 on 2023-11-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_taskassignment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='max_tasks_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
