# Generated by Django 4.2.7 on 2023-11-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee_max_tasks_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notifications_sent',
            field=models.IntegerField(default=0),
        ),
    ]
