# Generated by Django 4.2.7 on 2023-11-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_task_notifications_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeconfirmation',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
