# Generated by Django 4.2.7 on 2023-11-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_employee_max_tasks_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='skill_level',
            new_name='rating',
        ),
    ]
