# Generated by Django 4.2.7 on 2023-11-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_skill_level_employee_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeconfirmation',
            name='status',
        ),
    ]
