# Generated by Django 4.2.7 on 2023-11-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_employeeconfirmation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
