# Generated by Django 4.2.7 on 2023-11-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_notes_options_remove_notes_date_notes_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='datetime',
        ),
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
