# Generated by Django 4.2.7 on 2023-12-11 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_task_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='note',
        ),
        migrations.AddField(
            model_name='notes',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата и время напоминания'),
        ),
        migrations.AddField(
            model_name='notes',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст напоминания'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Сотрудник'),
        ),
    ]
